version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  snyk: snyk/snyk@2.0.1
  maven: circleci/maven@1.4.1

executors:
  default-executor:
    docker:
      - image: cimg/openjdk:17.0.8

# Set JAVA_HOME
env:
  JAVA_HOME: /home/regino_deang/.sdkman/candidates/java/current/bin/java  # Update the path to your Java installation

# Define jobs
jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Set JAVA_HOME
          command: echo 'export JAVA_HOME="/home/regino_deang/.sdkman/candidates/java/current"' >> $BASH_ENV
      - run:
          name: Update mvnw permissions
          command: chmod +x ./mvnw
      - run:
          name: Build Spring Boot App
          command: |
            source $BASH_ENV
            ./mvnw clean package -DskipTests
            mv target/pdt_sales-0.0.1-SNAPSHOT.jar app.jar

  test:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Run 8 Spring Boot Unit Tests in 2 Java Files
          command: |
            source $BASH_ENV
            mvn test

  synk_scan:
    executor: default-executor
    environment:
      IMAGE_NAME: lohcd/pdt_sales
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Update mvnw permissions
          command: chmod +x ./mvnw
      - run:
          name: Build Spring Boot App
          command: |
            source $BASH_ENV
            ./mvnw clean package -DskipTests
      - save_cache:
          key: app-jar-{{ checksum "pom.xml" }}
          paths:
            - ./target/pdt_sales-0.0.1-SNAPSHOT.jar
      - restore_cache:
          key: app-jar-{{ checksum "pom.xml" }}
      - run:
          name: Build Docker image
          command: |
            source $BASH_ENV
            docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
          severity-threshold: high

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: Update mvnw permissions
          command: chmod +x ./mvnw
      - run:
          name: Build Spring Boot App
          command: |
            source $BASH_ENV
            ./mvnw clean package -DskipTests
      - docker/build:
          image: reginodeang/pdt_sales:1.0
      - docker/push:
          image: reginodeang/pdt_sales:1.0

workflows:
  version: 2
  ci_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - synk_scan:
          requires:
            - build
      - build-and-push:
          requires:
            - test







